### ISSUE TITLE
Cache the results of open-aoc-input

### ISSUE THREAD

**Issue by IQubic** [eutro/advent-of-code-racket#2]
Since Eric Wastl, the maintainer of the AOC server, has requested that users not constantly send requests to the server, it makes sense to cache the results of `open-aoc-input` and only fetch data from the server when a local copy of the input doesn't exist. 

I recommend storing the input in the directory specified by `(find-system-path 'cache-dir)`

**Comment by eutro** [comment]
Implemented in 5306674175d0100d5d2b3ea5de43370e332a8dd0.
